/**
 * program.js — Anchor program setup and on-chain account helpers
 */

import { Connection, PublicKey } from "@solana/web3.js";
import { Buffer } from "buffer";
import { AnchorProvider, Program, BN } from "@coral-xyz/anchor";
import {
  getComputationAccAddress,
  getClusterAccAddress,
  getMXEAccAddress,
  getMempoolAccAddress,
  getExecutingPoolAccAddress,
  getFeePoolAccAddress,
  getClockAccAddress,
  getCompDefAccAddress,
  getCompDefAccOffset,
  getArciumProgramId,
} from "@arcium-hq/client";
import {
  PROGRAM_ID,
  RPC_URL,
  CLUSTER_OFFSET,
} from "./constants";

export const TOKEN_PROGRAM_ID = new PublicKey("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA");
export const ASSOCIATED_TOKEN_PROGRAM_ID = new PublicKey("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL");

// ── IDL import (generated by `arcium build`) ──
// In production this file is at target/idl/shieldlend_program.json
// For development you can import a stub — replace with the real IDL after build
let idl;
try {
  idl = (await import("../idl/shieldlend.json")).default;
} catch {
  // IDL not yet generated — placeholder for pre-build dev
  idl = { version: "0.1.0", name: "shieldlend_program", instructions: [], accounts: [], events: [], errors: [] };
}

// ─────────────────────────────────────────────────────────────
// PROGRAM INSTANCE
// ─────────────────────────────────────────────────────────────

/**
 * Build an Anchor Program instance using the connected wallet.
 *
 * @param {object} wallet - wallet adapter wallet object
 * @returns {{ program, provider, connection }}
 */
export function getProgram(wallet) {
  const connection = new Connection(RPC_URL, "confirmed");
  const provider = new AnchorProvider(connection, wallet, {
    commitment: "confirmed",
    preflightCommitment: "confirmed",
  });
  const program = new Program(idl, provider);
  console.log("[ShieldLend] Anchor program connected", {
    programId: PROGRAM_ID,
    rpcUrl: RPC_URL,
    wallet: wallet.publicKey?.toBase58?.(),
  });
  return { program, provider, connection };
}

// ─────────────────────────────────────────────────────────────
// ARCIUM PDA HELPERS
// ─────────────────────────────────────────────────────────────

/**
 * Derive all Arcium-required account addresses for a computation.
 *
 * @param {string|PublicKey} programId
 * @param {bigint|BN|number} computationOffset
 * @returns {object} Named account addresses
 */
export function getArciumAccounts(programId, computationOffset) {
  const offsetBN =
    computationOffset instanceof BN
      ? computationOffset
      : new BN(computationOffset.toString());

  const programPubkey = new PublicKey(programId);

  const [signPdaAccount] = PublicKey.findProgramAddressSync(
    [Buffer.from("ArciumSignerAccount")],
    programPubkey
  );

  const accounts = {
    computationAccount: getComputationAccAddress(CLUSTER_OFFSET, offsetBN),
    clusterAccount: getClusterAccAddress(CLUSTER_OFFSET),
    mxeAccount: getMXEAccAddress(programPubkey),
    mempoolAccount: getMempoolAccAddress(CLUSTER_OFFSET),
    executingPool: getExecutingPoolAccAddress(CLUSTER_OFFSET),
    poolAccount: getFeePoolAccAddress(),
    clockAccount: getClockAccAddress(),
    signPdaAccount,
    arciumProgram: getArciumProgramId(),
  };

  console.log("[ShieldLend] Derived Arcium accounts", {
    computationOffset: offsetBN.toString(),
    signPdaAccount: accounts.signPdaAccount.toBase58(),
    computationAccount: accounts.computationAccount.toBase58(),
    clusterAccount: accounts.clusterAccount.toBase58(),
    mxeAccount: accounts.mxeAccount.toBase58(),
    mempoolAccount: accounts.mempoolAccount.toBase58(),
    executingPool: accounts.executingPool.toBase58(),
    poolAccount: accounts.poolAccount.toBase58(),
    clockAccount: accounts.clockAccount.toBase58(),
    arciumProgram: accounts.arciumProgram.toBase58(),
  });

  return accounts;
}

/**
 * Derive the comp_def PDA for a given circuit name.
 *
 * @param {string|PublicKey} programId
 * @param {string} circuitName - e.g. "check_liquidatable"
 * @returns {PublicKey}
 */
export function getCompDefAddress(programId, circuitName) {
  const offsetBytes = getCompDefAccOffset(circuitName);
  const offset = Buffer.from(offsetBytes).readUInt32LE(0);
  const address = getCompDefAccAddress(new PublicKey(programId), offset);
  console.log("[ShieldLend] Derived computation definition", {
    circuitName,
    offsetBytes: Array.from(offsetBytes),
    offset,
    compDefAccount: address.toBase58(),
  });
  return address;
}

// ─────────────────────────────────────────────────────────────
// SHIELDLEND PDA HELPERS
// ─────────────────────────────────────────────────────────────

/**
 * Derive the position PDA for a user.
 *
 * Seeds: ["position", userPubkey]
 *
 * @param {string|PublicKey} programId
 * @param {string|PublicKey} userPubkey
 * @returns {PublicKey}
 */
export function getPositionAddress(programId, userPubkey) {
  const [pda] = PublicKey.findProgramAddressSync(
    [Buffer.from("position"), new PublicKey(userPubkey).toBuffer()],
    new PublicKey(programId)
  );
  return pda;
}

/**
 * Derive the protocol state PDA.
 *
 * Seeds: ["protocol"]
 *
 * @param {string|PublicKey} programId
 * @returns {PublicKey}
 */
export function getProtocolAddress(programId) {
  const [pda] = PublicKey.findProgramAddressSync(
    [Buffer.from("protocol")],
    new PublicKey(programId)
  );
  return pda;
}

/**
 * Derive the vault PDA.
 *
 * Seeds: ["vault"]
 *
 * @param {string|PublicKey} programId
 * @returns {PublicKey}
 */
export function getVaultAddress(programId) {
  const [pda] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault")],
    new PublicKey(programId)
  );
  return pda;
}

/**
 * Derive the shSOL receipt mint PDA.
 *
 * Seeds: ["shsol_mint"]
 *
 * @param {string|PublicKey} programId
 * @returns {PublicKey}
 */
export function getShsolMintAddress(programId) {
  const [pda] = PublicKey.findProgramAddressSync(
    [Buffer.from("shsol_mint")],
    new PublicKey(programId)
  );
  return pda;
}

/**
 * Derive the associated token account for a wallet/mint pair.
 *
 * @param {string|PublicKey} owner
 * @param {string|PublicKey} mint
 * @returns {PublicKey}
 */
export function getAssociatedTokenAddress(owner, mint) {
  const [ata] = PublicKey.findProgramAddressSync(
    [
      new PublicKey(owner).toBuffer(),
      TOKEN_PROGRAM_ID.toBuffer(),
      new PublicKey(mint).toBuffer(),
    ],
    ASSOCIATED_TOKEN_PROGRAM_ID
  );
  return ata;
}

/**
 * Fetch the raw protocol state account.
 *
 * @param {Program} program
 * @returns {Promise<object|null>}
 */
export async function fetchProtocolState(program) {
  try {
    const pda = getProtocolAddress(PROGRAM_ID);
    return await program.account.protocolState.fetch(pda);
  } catch {
    return null;
  }
}

/**
 * Fetch the user's position account.
 *
 * @param {Program} program
 * @param {string|PublicKey} userPubkey
 * @returns {Promise<object|null>}
 */
export async function fetchPosition(program, userPubkey) {
  try {
    const pda = getPositionAddress(PROGRAM_ID, userPubkey);
    return await program.account.userPosition.fetch(pda);
  } catch {
    return null;
  }
}
